version: "3"

networks:
  pm-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  pm-backend:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.10.2.0/23
  # default:
  #   external:
  #     name: nginx-proxy

services:
  pm-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    container_name: pm-db
    ports:
      - 3306:3306
    volumes:
      - pm-db:/var/lib/mysql
    networks:
      pm-backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./development.env
    restart: always
  pm-www:
    build: ./www
    expose:
      - 80
    # ports:
    #   - 8080:80
    container_name: pm-www
    volumes:
      - pm-www:/var/www/html/
    networks:
      pm-backend:
        ipv4_address: 172.10.2.2
      pm-frontend:
        ipv4_address: 172.10.1.2
    network_mode: nginx-proxy
    depends_on:
      - pm-db
    env_file:
      - ./development.env
    environment:
      VIRTUAL_HOST: kaunas3022.eu, www.kaunas3022.eu
    restart: always

volumes:
  pm-db:
  pm-www:
